let a = [1, 2, "sonu", true];
console.log(a);
let b = new Array(3);
b = [1, 2, "sonu", true];
console.log(b);
console.log(a[3]);
let c = [1, 2, 3, 4, 5, 6, 7, 8, 9];
c.push(4);
console.log(c);
c.pop();
console.log(c);
c.shift();
console.log(c);
c.unshift(6);
console.log(c);